# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'New Entry'), ('E', 'Updated Entry')], max_length=2)),
                ('field', models.CharField(max_length=30)),
                ('previous_data', models.TextField()),
                ('new_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('school_name', models.CharField(max_length=200)),
                ('url_address', models.TextField()),
                ('address', models.TextField()),
                ('postal_code', models.TextField()),
                ('telephone_no', models.TextField()),
                ('telephone_no2', models.TextField()),
                ('fax_no', models.TextField()),
                ('fax_no2', models.TextField()),
                ('email_address', models.TextField()),
                ('mrt_desc', models.TextField()),
                ('bus_desc', models.TextField()),
                ('principal_name', models.TextField()),
                ('first_vp_name', models.TextField()),
                ('second_vp_name', models.TextField()),
                ('third_vp_name', models.TextField()),
                ('fourth_vp_name', models.TextField()),
                ('fifth_vp_name', models.TextField()),
                ('visionstatement_desc', models.TextField()),
                ('missionstatement_desc', models.TextField()),
                ('philosophy_culture_ethos', models.TextField()),
                ('dgp_code', models.TextField()),
                ('zone_code', models.TextField()),
                ('cluster_code', models.TextField()),
                ('type_code', models.TextField()),
                ('nature_code', models.TextField()),
                ('session_code', models.TextField()),
                ('mainlevel_code', models.TextField()),
                ('sap_ind', models.TextField()),
                ('autonomous_ind', models.TextField()),
                ('gifted_ind', models.TextField()),
                ('ip_ind', models.TextField()),
                ('mothertounge1_code', models.TextField()),
                ('mothertounge2_code', models.TextField()),
                ('mothertounge3_code', models.TextField()),
                ('special_sdp_offered', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
