# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170930_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='fax_no2',
            new_name='fax_no_2',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='mothertounge1_code',
            new_name='mothertongue1_code',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='mothertounge2_code',
            new_name='mothertongue2_code',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='mothertounge3_code',
            new_name='mothertongue3_code',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='telephone_no2',
            new_name='telephone_no_2',
        ),
    ]
