# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170930_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerlog',
            name='type',
            field=models.CharField(choices=[('N', 'New Entry'), ('U', 'Updated Entry')], max_length=2),
        ),
    ]
