# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import sso.models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', sso.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='custom_token',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('username',)]),
        ),
    ]
